server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.php index.html index.htm;

    # Обработка статики напрямую
    location /public/ {
        try_files $uri $uri/ =404;
        expires 30d;
        access_log off;
    }

    # Все остальные запросы на единую точку входа (индекс)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Запрет доступа к внутренним папкам
    location ~ ^/(templates|includes|docker)/ {
        deny all;
        return 404;
    }

    # PHP-FPM
    location ~ \.php$ {
        fastcgi_pass    127.0.0.1:9000;
        fastcgi_index   index.php;
        fastcgi_param   SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include         fastcgi_params;
    }

    location ~ /\. {
        deny all;
    }

    access_log /var/log/nginx/web_access.log;
    error_log  /var/log/nginx/web_error.log;
}
